# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 736a54e5daf2a38d9b45182dd9059ba24ead10e2cc919973fd2be355164a45e0b81f5e4f2f8e7964d66d796f8b416aa7e9f3ea513a91202f1ef84ba2d933e7ec

test:
  secret_key_base: b853950cdbf07e10b6e7e736137584bb4e1a07af89cd2b7c10ddbedf2d68279aebdb49235b0cbb221770ded045df1c63d3c8424c1a7547bdcd1c226637c8b355

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
